# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0003_auto_20170120_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='namexx',
            new_name='name',
        ),
    ]
